export const SET_IMAGES_ORDER_REQUEST = 'SET_IMAGES_ORDER_REQUEST';
export const SET_IMAGES_ORDER_SUCCESS = 'SET_IMAGES_ORDER_SUCCESS';
export const SET_IMAGES_ORDER_FAILURE = 'SET_IMAGES_ORDER_FAILURE';
